import "./Project.css";

function Project() {
  const projects = [
    {
      title: "AI vs Human Text Detection",
      image: "https://via.placeholder.com/600x350",
      description:
        "An intelligent text classification system that analyzes written content and predicts whether it was generated by an AI model or authored by a human using machine learning techniques.",
      tech: ["Machine Learning", "HTML", "CSS", "Flask"],
      github:
        "https://github.com/radhakrishnaanamika890-max/AI-vs-Human-Text-Detection",
    },

    {
      title: "AI Platform Performance",
      image: "https://via.placeholder.com/600x350",
      description:
        "An interactive Tableau dashboard that visualizes and compares the performance of various AI platforms through insightful charts, trends, and data-driven analytics.",
      tech: ["Tableau"],
      github:
        "https://github.com/radhakrishnaanamika890-max/AI-Platform-Performance-using-Tableau",
    },

    {
      title: "Online Food Survey",
      image: "https://via.placeholder.com/600x350",
      description:
        "A comprehensive Tableau-based survey analysis project that explores customer preferences, ordering behavior, and satisfaction trends in online food delivery services.",
      tech: ["Tableau"],
      github:
        "https://github.com/radhakrishnaanamika890-max/Online-Food-using-Tableau",
    },
  ];

  return (
    <section className="projects" id="projects">
      <h1 className="project-title">Featured Projects</h1>

      <div className="project-container">
        {projects.map((project, index) => (
          <div className="project-card" key={index}>
            <div className="project-image">
              <img src={project.image} alt={project.title} />
            </div>

            <div className="project-content">
              <h2>{project.title}</h2>

              <p>{project.description}</p>

              <div className="tech-stack">
                {project.tech.map((tech, i) => (
                  <span key={i}>{tech}</span>
                ))}
              </div>

              <a
                href={project.github}
                target="_blank"
                rel="noreferrer"
                className="github-btn"
              >
                GitHub Repository
              </a>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

export default Project;